version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db_cryptography
    restart: always
    environment:
      POSTGRES_DB: cryptography
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
